### ISSUE TITLE
Review Comments

### ISSUE THREAD

**Issue by raghuprathap** [HariPrasadMvsk/capsule-project#1]
1. On typing some text onto chat input and click on enter gettign below error.
![image](https://user-images.githubusercontent.com/3498847/45859188-a36a9400-bd7e-11e8-8758-b17a41a86143.png)
2. There should be a provision to create public / private room and add members to it.
3. Enzyme test cases are missing.
4. If there are some pre created users are list them or create new user facility.
5. show indication if user is online.
6. CI/CD pipeline missing.

**Comment by HariPrasadMvsk** [comment]
Hi @raghuprathap,
Fixed all the review comments.
Thanks,
Hari Prasad

**Comment by raghuprathap** [comment]
![image](https://user-images.githubusercontent.com/3498847/46058808-1f4b4e80-c17a-11e8-9e87-b38b97e3fc69.png)
CI/CD pipeline CD is failing.
