### ISSUE TITLE
Second level review comments

### ISSUE THREAD

**Issue by raghuprathap** [HariPrasadMvsk/capsule-project#2]
![image](https://user-images.githubusercontent.com/3498847/46058851-4b66cf80-c17a-11e8-995d-11c7f76355fb.png)

CI/CD pipeline CD failing.

**Comment by HariPrasadMvsk** [comment]
Hi @raghuprathap,
Fixed and check-in done.

Thanks,
Hari Prasad.

**Comment by HariPrasadMvsk** [comment]
Fixed
